# Generated by Django 3.2.9 on 2021-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_rename_atracoes_eventoscomplementos'),
        ('core', '0002_alter_pontoturistico_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='complementos',
            field=models.ManyToManyField(to='atracoes.EventosComplementos'),
        ),
    ]
