# Generated by Django 3.2.9 on 2021-11-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pontoturistico_aprovado'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracoes',
            new_name='EventosComplementos',
        ),
    ]
