# Generated by Django 3.2.9 on 2022-01-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontoturistico_endereco'),
        ('atracoes', '0002_rename_atracoes_eventoscomplementos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventosComplementos',
            new_name='Atracao',
        ),
    ]
